### ISSUE TITLE
GraphiQL JS error with tartiflette 1.0RC1

### ISSUE THREAD

**Issue by aljinovic** [tartiflette/tartiflette#284]
I've been testing the tartiflette RC1 (https://github.com/tartiflette/tartiflette/pull/272) with tartiflette-aiohttp and noticed that GraphiQL crashes with this error:

```
GraphQLError: Syntax Error: Expected <EOF>, found Name "longer"
    at syntaxError (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:23522:10)
    at expect (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:28513:32)
    at parseValue (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:27279:3)
    at buildInputValue (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33676:118)
    at https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25955:31
    at Array.reduce (<anonymous>)
    at keyValMap (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25954:15)
    at buildInputValueDefMap (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33669:36)
    at buildDirective (https://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33696:13)
    at Array.map (<anonymous>)
```

**Comment by Maximilien-R** [comment]
Hi @aljinovic,

I have some good news. I have dug into the issue and find out that the error wasn't due to the parsing of `StringValue` and `BlockString` (even if we didn't handle them properly) but to the resolving process of the `__InputValue.defaultValue` field.

Indeed, the [GraphQL specification](https://graphql.github.io/graphql-spec/June2018/#sec-The-__InputValue-Type) isn't very clear about it (IMO). The resolved value has to be a parsable GraphQL literal value instead of just a string.

Anyway, this commit https://github.com/tartiflette/tartiflette/pull/272/commits/e73cb0c0b997a4698024db7015229d683c13ee16 should fix this issue.

You can test it with this development release:
```
pip install --extra-index-url https://test.pypi.org/simple/ tartiflette==1.0.0rc1.dev1568023843
```
